# Generated by Django 5.0.6 on 2024-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0010_watchmans_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmans',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
