# Generated by Django 5.0.6 on 2024-07-15 07:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('student', '0004_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remaining_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('I', 'Incomplete'), ('P', 'Partial-Complete'), ('C', 'Complete')], default='I', max_length=10)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.technology')),
            ],
            options={
                'unique_together': {('student_id', 'technology_id')},
            },
        ),
    ]
