# Generated by Django 5.0.6 on 2024-07-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentpaymententry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpaymententry',
            old_name='stdent_id',
            new_name='student_id',
        ),
    ]
