# Generated by Django 5.0.6 on 2024-07-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_rename_stdent_id_studentpaymententry_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymententry',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
    ]
