# Generated by Django 5.0.6 on 2024-07-15 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_studentpaymententry_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpaymententry',
            name='installment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
