# Generated by Django 5.0.6 on 2024-06-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeprofile'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('batch_name', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
