# Generated by Django 5.0.6 on 2024-06-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_productsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('information_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='master.information')),
                ('customer_id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=255)),
            ],
            bases=('master.information',),
        ),
    ]
