# Generated by Django 5.0.6 on 2024-06-24 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('student', '0005_alter_studentpayment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_start_date', models.DateField()),
                ('batch_end_date', models.DateField()),
                ('batch_status', models.CharField(choices=[('S', 'Start-Course'), ('E', 'End-Course')], max_length=20)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('technology_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
