# Generated by Django 5.0.6 on 2024-06-24 14:54

import django.db.models.deletion
import django.utils.timezone
import master.utils.TA_UNIQE.uniques_filename
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPaymentEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('proof', models.ImageField(upload_to=master.utils.TA_UNIQE.uniques_filename.generate_unique_filename)),
                ('paid_date', models.DateField(default=django.utils.timezone.now)),
                ('installment', models.FloatField(default=0.0)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
