# Generated by Django 5.0.6 on 2024-06-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='master.basemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('name',)},
            },
            bases=('master.basemodel',),
        ),
    ]
