# Generated by Django 5.0.6 on 2024-07-03 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0007_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visitors',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
