# Generated by Django 5.0.6 on 2024-07-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0008_visitors_entry_time_visitors_exit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
