# Generated by Django 5.0.6 on 2024-07-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0009_members_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchmans',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='society.role'),
            preserve_default=False,
        ),
    ]
