# Generated by Django 5.0.6 on 2024-06-23 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_assignbatch'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='technology_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.technology'),
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
